version: "3.3"

services:

  cead_server:
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - variables.env
    build:
      context: ./
    ports:
      - "${PORT}:8000"
    volumes:
      - ./landing:/landing
      - cead:/tmp/cead_db
      - media:/landing/media
    container_name: cead_server
    depends_on:
      - cead_db
    entrypoint: ["/bin/bash", "run.sh"]

  cead_db:
    env_file:
      - variables.env
    image: postgres:13.1
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      interval: 10s
      timeout: 45s
      retries: 10
    expose:
      - "5656"
    volumes:
      - backups:/var/lib/postgresql/data
    container_name: cead_db
    command: -p 5656
    ports:
      - "5656:5656"

volumes:
  cead:
  media:
  backups:
