# Generated by Django 3.2.12 on 2022-10-25 05:23

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='heading',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='ads',
            field=wagtail.core.fields.StreamField([('ad', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(label='Texto do anúncio', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagem do anúncio', required=True)), ('link', wagtail.core.blocks.URLBlock(label='Link', required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='schedulling_btn_text',
            field=models.CharField(default='Realizar agendamento', max_length=256),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='schedulling_subtext',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
