# Generated by Django 3.2.12 on 2022-10-25 14:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmetadata.models
import wagtailstreamforms.blocks
from wagtail.core.models import Page, Site
from home.models import LandingPage

def create_set_home_page(apps, schema_editor):
    root = Page.get_first_root_node()

    home_page = LandingPage(title="Home")

    root.add_child(instance=home_page)
    root.save()

    site = Site.objects.get(id=1)
    site.root_page = home_page
    site.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_set_home_page)
    ]
